cp -rf ../NetCloud/cmd ./ 
cp -rf ../NetCloud/pkg ./ 
cp -rf ../NetCloud/config ./ 
cp -rf ../NetCloud/internel/app/api ./internel/ 
cp -rf ../NetCloud/internel/app/config ./internel/ 
cp -rf ../NetCloud/internel/app/contextx ./internel/ 
cp -rf ../NetCloud/internel/app/dao ./internel/ 
cp -rf ../NetCloud/internel/app/ginx ./internel/ 
cp -rf ../NetCloud/internel/app/middleware ./internel/ 
cp -rf ../NetCloud/internel/app/*.go ./internel/ 
